workspace:
  base: /go
  path: src/github.com/presslabs/wordpress-operator

pipeline:
  test:
    image: golang:1.10
    commands:
      - make dependencies
      - make lint
      - make test

  publish:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/wordpress-operator
    tags: [ "latest" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      branch: master
      event: push

  publish:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/presslabs/wordpress-operator
    tags: [ "${DRONE_TAG}" ]
    username: presslabs+drone
    secrets:
      - source: QUAY_TOKEN
        target: DOCKER_PASSWORD
    when:
      event: tag
