---
kind: pipeline
name: build

clone:
  disable: true

workspace:
  base: /root/go
  path: src/github.com/presslabs/wordpress-operator

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: dependencies
  pull: always
  image: quay.io/presslabs/bfc
  commands:
  - make dependencies

- name: verify
  image: quay.io/presslabs/bfc
  commands:
  - make -s fmt generate manifests
  - git diff --exit-code

- name: lint
  image: quay.io/presslabs/bfc
  commands:
  - make lint
  - helm lint chart/wordpress-operator
  - helm dep build chart/wordpress-operator

- name: build
  image: quay.io/presslabs/bfc
  commands:
  - make chart
  - make test

- name: publish docker image
  image: plugins/docker
  settings:
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/wordpress-operator
    tags:
    - ${DRONE_BRANCH/master/latest}
    - ${DRONE_COMMIT_SHA:0:7}
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN
  when:
    event:
      - push
---
kind: pipeline
name: publish

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 0
    tags: true

- name: publish docker image
  image: plugins/docker
  settings:
    group: publish
    registry: quay.io
    repo: quay.io/presslabs/wordpress-operator
    auto_tag: true
    username: presslabs+drone
  environment:
    DOCKER_PASSWORD:
      from_secret: QUAY_TOKEN

- name: publish helm chart
  pull: default
  image: quay.io/presslabs/bfc
  commands:
  - make chart
  - cd chart
  - helm package wordpress-operator
  - CHART="$(basename *.tgz)" ; MESSAGE="Publish $(basename $CHART .tgz)"
  - /usr/local/bin/gh put --skip-existing -m "$MESSAGE" "$CHART" "presslabs/charts/docs/"
  settings:
    group: publish
  environment:
    GH_PASSWORD:
      from_secret: GH_PASSWORD
    GH_USER: presslabs-bot

trigger:
  event:
  - tag
