apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: wordpresspolicies.wordpress.presslabs.org
spec:
  group: wordpress.presslabs.org
  names:
    kind: WordpressPolicy
    plural: wordpresspolicies
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            priority:
              format: int32
              type: integer
            selector:
              type: object
            template:
              properties:
                metadata:
                  type: object
                spec:
                  properties:
                    cliPodTemplate:
                      type: object
                    env:
                      items:
                        type: object
                      type: array
                    envFrom:
                      items:
                        type: object
                      type: array
                    ingressAnnotations:
                      type: object
                    mediaVolumeSpec:
                      properties:
                        emptyDir:
                          type: object
                        hostPath:
                          type: object
                        persistentVolumeClaim:
                          type: object
                      type: object
                    serviceSpec:
                      type: object
                    tlsSecretRef:
                      type: string
                    volumeMountsSpec:
                      items:
                        type: object
                      type: array
                    webPodTemplate:
                      type: object
                    webrootVolumeSpec:
                      properties:
                        emptyDir:
                          type: object
                        hostPath:
                          type: object
                        persistentVolumeClaim:
                          type: object
                      type: object
                  type: object
              type: object
          required:
          - template
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
